### PR TITLE
Stopped 'Slimefun' Infernal Dust dropping

### LINKED ISSUE #74: Infernal dusts - double names
## :round_pushpin: Description (REQUIRED)

Hi, when players kill blazes they get sometimes different types of internal dust (with different nbt probably). Then they cannot be stacked.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

Kill blazes and you will probably get these two types of infernal dust.

## :bulb: Expected behavior (REQUIRED)

Just one infernal dust item.

## :scroll: Screenshots

image
image
image
image

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Purpur
 - Minecraft Version: 1.16.5
 - SensibleToolbox Version: 39

### PR DESCRIPTION
**Pull request by Sefiraat**
## Description
Infernal Dust drops two different stack types, one from STB's Drop and another from the MobDrop recipe type in Slimefun. The Slimefun drop includes Slimefun data making the two items not stack. This also inflates the drop rate beyond what is intended within STB.

## Changes
Created a new 'dummy' recipe type to look the same as Slimefun's MobDrop recipe type for display on the guide without triggering Slimefun's drops.

## Related Issues
Resolves #74

## Checklist
- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/slimefun/SlimefunBridge.java [hunk 1]
```diff
@@ -31,6 +31,8 @@
 
 public final class SlimefunBridge implements SlimefunAddon {
 
+    public static final RecipeType RECIPE_TYPE_MOB_DROP = new RecipeType(new NamespacedKey(SensibleToolboxPlugin.getInstance(), "mob_drop"), new CustomItem(Material.IRON_SWORD, "&bMob Drop", "&7Kill that Mob to", "&7obtain this Item"));
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/slimefun/SlimefunBridge.java:34]: This should not be static, move it to the other recipe types below please.

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/slimefun/SlimefunBridge.java (hunk 1 above)
Comment (Sefiraat) [reply src/main/java/io/github/thebusybiscuit/sensibletoolbox/slimefun/SlimefunBridge.java]: Done, thanks

**Review by TheBusyBiscuit — APPROVED** [review]
