### PR TITLE
Fix issue with elevators

### LINKED ISSUE #11: Going up an elevator does not work
## :round_pushpin: Description (REQUIRED)

Normally when you jump, you go up the elevator. But you just jump instead.
Going down by pressing crouch works just fine.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Place an elevator
2. Place another elevator some blocks above it
3. Step on the lower elevator
4. Jump

## :bulb: Expected behavior (REQUIRED)

I expected to go up the elevator

## :scroll: Server Log

No errors

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper (git-204)
 - Minecraft Version: 1.16.3
 - SensibleToolbox Version: DEV - 1 @ b0ab4a746c79db37a6f8077cb73bb5906fc72488

### PR DESCRIPTION
**Pull request by MrWouterNL**
## Description
Resolved issue #11, the source of the issue was ``((Entity) event.getPlayer()).isOnGround()`` returning false. 

## Changes
* Fix issue 11 by adding a replacement method for Entity#isOnGround() to resolve the issue

## Related Issues

Resolves #11 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

### CODE REVIEW

**Review by Sfiguz7 — DISMISSED** [review]

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/listeners/ElevatorListener.java [hunk 1]
```diff
@@ -65,4 +67,10 @@ public void onPlayerSneak(PlayerToggleSneakEvent event) {
         }
     }
 
+    private boolean isOnGround(@Nonnull Player player) {
+        Location location = player.getLocation();
+        Block currentBlock = location.getBlock();
+        return currentBlock.getRelative(BlockFace.DOWN) != null && location.getY() == location.getBlockY();
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/listeners/ElevatorListener.java:73]: [Block#getRelative()](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Block.html#getRelative(org.bukkit.block.BlockFace)) is marked as `@NotNull`, so this null check here is redundant and will never be null.

You probably meant to do `Block#isEmpty()` for the block below.

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/listeners/ElevatorListener.java (hunk 1 above)
Comment (MrWouterNL) [reply src/main/java/io/github/thebusybiscuit/sensibletoolbox/listeners/ElevatorListener.java]: Resolved

**Review by LinoxGH — APPROVED** [review]

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/listeners/ElevatorListener.java [hunk 2]
```diff
@@ -65,4 +67,10 @@ public void onPlayerSneak(PlayerToggleSneakEvent event) {
         }
     }
 
+    private boolean isOnGround(@Nonnull Player player) {
+        Location location = player.getLocation();
+        Block currentBlock = location.getBlock();
+    	return !currentBlock.getRelative(BlockFace.DOWN).isEmpty() && location.getY() == location.getBlockY();
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/listeners/ElevatorListener.java:73]: Nitpicky but the indentation is a little off here :eyes:

Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/listeners/ElevatorListener.java:73]: I am feeling comfortable with these changes overall.
However one thing I would definitely like to have changed before merging this is the floating point comparison at the end.
`.getY()` will return a floating point value (double), so this comparison will be subject to floating point value errors.
I think the best way to circumvent this would be to check if the distance between these two numbers is below a very small number.

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/listeners/ElevatorListener.java (hunk 2 above)
Comment (MrWouterNL) [reply src/main/java/io/github/thebusybiscuit/sensibletoolbox/listeners/ElevatorListener.java:73]: How small would be comfortable? In my testing this worked as expected but I understand your concern. Would something like 0.05 suffice or would you prefer something lower?

Comment (LinoxGH) [reply src/main/java/io/github/thebusybiscuit/sensibletoolbox/listeners/ElevatorListener.java:73]: 0.05 would be fine

Comment (TheBusyBiscuit) [reply src/main/java/io/github/thebusybiscuit/sensibletoolbox/listeners/ElevatorListener.java:73]: I think something like 0.001 or such might be required, but feel free to test out 2 or 3 values. It should approximate zero, that's all.

Comment (LinoxGH) [reply src/main/java/io/github/thebusybiscuit/sensibletoolbox/listeners/ElevatorListener.java:73]: > I think something like 0.001 or such might be required, but feel free to test out 2 or 3 values. It should approximate zero, that's all.

That's not that required actually. Even 0.05 means less than a pixel of a block. If you are that low you practically are on ground.

Comment (TheBusyBiscuit) [reply src/main/java/io/github/thebusybiscuit/sensibletoolbox/listeners/ElevatorListener.java:73]: Oh okay then

Comment (MrWouterNL) [reply src/main/java/io/github/thebusybiscuit/sensibletoolbox/listeners/ElevatorListener.java:73]: Haha, I noticed this aswell. Will fix in next commit

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/listeners/ElevatorListener.java [hunk 3]
```diff
@@ -65,4 +67,10 @@ public void onPlayerSneak(PlayerToggleSneakEvent event) {
         }
     }
 
+    private boolean isOnGround(@Nonnull Player player) {
+        Location location = player.getLocation();
+        Block currentBlock = location.getBlock();
+        return !currentBlock.getRelative(BlockFace.DOWN).isEmpty() && Math.abs(location.getY() - location.getBlockY()) < 0.05;
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/listeners/ElevatorListener.java:73]: The `Math.abs()` is redundant here, since you already determined the direction of the movement to be upwards in line 28. So you can omit this call.

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

**Review by TheBusyBiscuit — APPROVED** [review]

**Review by LinoxGH — APPROVED** [review]
