### PR TITLE
Bug/sign types

### LINKED ISSUE #12: Placing a display sign will always result in oak wall signs
## :round_pushpin: Description (REQUIRED)

When you left click a machine with a sign, a display sign is placed. This also works for other types of signs but it will always place an oak sign, no matter the type of sign used.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Left click a machine with a sign to place a display sign
2. Notice the placed sign being always made of oak

## :bulb: Expected behavior (REQUIRED)

I expected it to place the correct type of sign.

## :scroll: Server Log

No errors in the console.

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper (git-204)
 - Minecraft Version: 1.16.3
 - SensibleToolbox Version: DEV - 1 @ b0ab4a746c79db37a6f8077cb73bb5906fc72488

### PR DESCRIPTION
**Pull request by MMJ744**
Modified methods that create label signs and created a util method to get the wall sign from the material of the sign.

## Description

To add support for all types of signs, placeLabelSign now takes a Material signType as another parameter to specify the type of the sign to palce.

attachLabelSign gets this type from the type of the sign in the players hand, using the util method getWallSign()

reattachLabelSign attempts to get the sign from the existing block data, if there is none it defaults to Oak.

moveTo gets the sign types from the old block and passes them into a scheduled task to then set them as before. This method also prevents extra processing from the piston bug causing piston events to fire multiple times.

## Changes

- Created the getWallSign util method in STBUtil.
- Changed palceLabelSign to take an extra parameter signType to specify the type of the sign to add.
- Changed the section of moveTo that deals with Label signs to support the new signType parameter.
- Changed reattachLabelSigns to support the new signType parameter.
- Changed the attachLabelSign to get the type of the sign from the players hand and support the new parameter.

## Related Issues

Resolves #12

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behavior for null values

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/util/STBUtil.java [hunk 1]
```diff
@@ -723,4 +723,35 @@ public static boolean isPotionIngredient(Material type) {
...
+            case JUNGLE_SIGN:
+                return Material.JUNGLE_WALL_SIGN;
+            case ACACIA_SIGN:
+                return Material.ACACIA_WALL_SIGN;
+            case DARK_OAK_SIGN:
+                return Material.DARK_OAK_WALL_SIGN;
+            case CRIMSON_SIGN:
+                return Material.CRIMSON_WALL_SIGN;
+            case WARPED_SIGN:
+                return Material.WARPED_WALL_SIGN;
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/util/STBUtil.java:752]: Sensible Toolbox supports 1.14-1.16, so this might throw an exception on 1.14/1.15 here.
I can't really think of a really good way to approach this at the moment, so I'd suggest to use a string comparison for now and refactor it late unless you have a better idea how to account for this.

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
Looking pretty good as it is, just some minor changes I'd like to request.
Thanks for tackling this issue :heart:

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/api/items/BaseSTBBlock.java [hunk 2]
```diff
@@ -985,17 +1003,22 @@ private boolean attachLabelSign(PlayerInteractEvent event) {
         return true;
     }
 
-    private boolean placeLabelSign(Block signBlock, BlockFace face) {
+    private boolean placeLabelSign(Block signBlock, BlockFace face, @Nonnull Material signType) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/api/items/BaseSTBBlock.java:1006]: The other two parameters can be marked as `@Nonnull` too I think

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/api/items/BaseSTBBlock.java [hunk 3]
```diff
@@ -985,17 +1003,22 @@ private boolean attachLabelSign(PlayerInteractEvent event) {
...
+        Validate.notNull(signType);
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/api/items/BaseSTBBlock.java:1007]: Please add a message to the validation
```suggestion
        Validate.notNull(signType, "The Sign Type cannot be null");
```

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/util/STBUtil.java [hunk 4]
```diff
@@ -723,4 +729,36 @@ public static boolean isPotionIngredient(Material type) {
...
+    /**
+     * Get the wall sign version of the sign material e.g. OAK_SIGN -> OAK_WALL_SIGN
+     *
+     * @param signType
+     *                 The material of the sign
+     * @return The wall sign version of that sign
+     */
+    @Nullable
+    public static Material getWallSign(@Nonnull Material signType) {
+        Validate.notNull(signType);
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/util/STBUtil.java:742]: Please add a message to the validation
```suggestion
        Validate.notNull(signType, "The Sign Type cannot be null");
```

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
These should be the last changes I'll be requesting.
Looks good though!

**Review by TheBusyBiscuit — APPROVED** [review]
LGTM, thank you

**Review by poma123 — APPROVED** [review]
LGTM, though there could be a better MinecraftVersion thing in the future, like the one used in SF

**Comment by TheBusyBiscuit** [comment]
@poma123 I was gonna refactor it and copy the Minecraft Version management thing from Slimefun later on, I mean you can do too if you want XD
But yeah, that's a bit out of scope here and we're probably gonna need the minecraft version checks in many places, so this definitely works for now.
