### PR TITLE
Fixed duplication error and updated to use new horse/cat classes

### LINKED ISSUE #9: Ender Leash can be used to duplicate mobs
## :round_pushpin: Description (REQUIRED)

I have only tested this with turtles so far but the main problem seems to be that the interaction is called twice, probably for the main hand and the offset hand.
With results in the mob being captured but also released at the same time, the ItemStack is updated incoherently, which makes the mob duplicate.

Here is a video illustration:
[GIF](https://gyazo.com/1f61ba5207751fa374f0df5c6504faf9)

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Take an Ender Leash, hold it in your main hand with nothing in the off hand
2. Right click a turtle

## :bulb: Expected behavior (REQUIRED)

The turtle should have been removed.

## :scroll: Server Log

*No significant data in the logs*

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper (git-204)
 - Minecraft Version: 1.16.3
 - SensibleToolbox Version: DEV - 1 @ b0ab4a746c79db37a6f8077cb73bb5906fc72488

### PR DESCRIPTION
**Pull request by MMJ744**
## Description

Added an extra field to the capture config containing the time of the capture.
Only let the entity be thawed if it was captured at least 1 tick (50ms) ago.
Updated old/depreciated code.
## Changes

- Used the updated method to get the item in the players main hand.
- Before thawing checked that the entity was captured more than 50ms ago.
- Added the capture time of the entity to the capture config in freezeEntity.
- Updated the freezeEntity method to use new API methods and no depreciated methods.
- Updated the thawEntity method to use the new API methods and no depreciated methods.

## Related Issues

Resolves #9 
## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java [hunk 1]
```diff
@@ -103,7 +108,7 @@ public boolean hasGlow() {
     public void onInteractEntity(PlayerInteractEntityEvent event) {
         Entity target = event.getRightClicked();
         Player player = event.getPlayer();
-        if (target instanceof Animals && isPassive(target) && player.getItemInHand().getAmount() == 1) {
+        if (target instanceof Animals && isPassive(target) && player.getInventory().getItemInMainHand().getAmount() == 1) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java:111]: This event can be invoked twice, with the off- and the main hand, so you'd need to check for both, by using the appropriate item based on the output of `event.getHand()`

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java [hunk 2]
```diff
@@ -155,6 +160,9 @@ private boolean checkLeash(Animals animal) {
     public void onInteractItem(PlayerInteractEvent event) {
         if (event.getAction() == Action.RIGHT_CLICK_BLOCK && !event.getClickedBlock().getType().isInteractable()) {
             if (capturedConf != null && capturedConf.contains("type")) {
+                if(System.currentTimeMillis() - capturedConf.getLong("capture_time") < 50) { // Less than 1 tick ago
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java:163]: I kinda dislike this magic number, could you please make that a `private static final` constant?

Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java:163]: Also, comments should always go above the code, never next to it.

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java [hunk 3]
```diff
@@ -179,8 +187,9 @@ private YamlConfiguration freezeEntity(Animals target) {
         conf.set("ageLock", target.getAgeLock());
         conf.set("name", target.getCustomName() == null ? "" : target.getCustomName());
         conf.set("nameVisible", target.isCustomNameVisible());
-        conf.set("maxHealth", target.getMaxHealth());
+        conf.set("maxHealth", target.getAttribute(Attribute.GENERIC_MAX_HEALTH).getValue());
         conf.set("health", target.getHealth());
+        conf.set("capture_time", System.currentTimeMillis());
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java:192]: Nitpicky but all other keys seem to follow the camelCase standard, so this one snake_case exception here is a bit bothersome XD

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java [hunk 4]
```diff
@@ -193,8 +202,9 @@ private YamlConfiguration freezeEntity(Animals target) {
             conf.set("sheared", ((Sheep) target).isSheared());
             conf.set("color", ((Sheep) target).getColor().toString());
             break;
-        case OCELOT:
-            conf.set("catType", ((Ocelot) target).getCatType().toString());
+        case CAT:
+            conf.set("catType", ((Cat) target).getCatType().toString());
+            conf.set("setCollarColor", ((Cat) target).getCollarColor().toString());
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java:207]: ehh why "set" ?

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java [hunk 5]
```diff
@@ -204,14 +214,21 @@ private YamlConfiguration freezeEntity(Animals target) {
             conf.set("sitting", ((Wolf) target).isSitting());
             break;
         case HORSE:
-            Horse h = (Horse) target;
-            conf.set("horseStyle", h.getStyle().toString());
-            conf.set("horseVariant", h.getVariant().toString());
-            conf.set("horseColor", h.getColor().toString());
-            conf.set("chest", h.isCarryingChest());
+        case MULE:
+        case DONKEY:
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java:218]: You could also add Skeleton horses and zombie horses here

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java (hunk 1 above)
Comment (MMJ744) [reply src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java:111]: Ah yes I missed this as it doesn't trigger twice with leashable animals, only others like turtles. It can't actually be used in the offhand slot though as it does not trigger the event. Should I just only allow the event to proceed if it is from the main hand? Currently if its in your offhand it never triggers the event, but will act as a normal leash for leashable animals.

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java (hunk 4 above)
Comment (MMJ744) [reply src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java:207]: That was a silly typo.. which lead me to find another, glad you caught that.

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java (hunk 1 above)
Comment (TheBusyBiscuit) [reply src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java:111]: Ah, that explains this inconsistency I experienced with turtles.
In that case yes, simply ignore sll offhand events.

Comment (MMJ744) [reply src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java:111]: What about adding a listener for PlayerLeashEntityEvent to prevent it being used as a normal leash when in the offhand, or shall I just ignore that?

Comment (MMJ744) [reply src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java]: Ok so unfortunately it seems that the PlayerLeashEntityEvent also wont trigger from the offhand. I don't really understand how these events are registered and when they will and wont trigger but it seems with the current system this isn't possible. 

This isn't really a big issue, but if you do try to use it on a leashable animal from the offhand with nothing in the main hand. It will leash the animal as usual and on dropping turn back into a normal leash. I could always make an issue for this if required.

**Review by TheBusyBiscuit — APPROVED** [review]

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java [hunk 6]
```diff
@@ -103,7 +109,7 @@ public boolean hasGlow() {
     public void onInteractEntity(PlayerInteractEntityEvent event) {
         Entity target = event.getRightClicked();
         Player player = event.getPlayer();
-        if (target instanceof Animals && isPassive(target) && player.getItemInHand().getAmount() == 1) {
+        if (event.getHand()==EquipmentSlot.HAND && target instanceof Animals && isPassive(target) && player.getInventory().getItemInMainHand().getAmount() == 1) {
```
Comment (LinoxGH) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java:112]:
```suggestion
        if (event.getHand() == EquipmentSlot.HAND && target instanceof Animals && isPassive(target) && player.getInventory().getItemInMainHand().getAmount() == 1) {
```

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java [hunk 7]
```diff
@@ -155,6 +161,10 @@ private boolean checkLeash(Animals animal) {
     public void onInteractItem(PlayerInteractEvent event) {
         if (event.getAction() == Action.RIGHT_CLICK_BLOCK && !event.getClickedBlock().getType().isInteractable()) {
             if (capturedConf != null && capturedConf.contains("type")) {
+                // Check enough time has passed since freezing entity
+                if(System.currentTimeMillis() - capturedConf.getLong("captureTime") < MIN_THAW_DELAY) {
```
Comment (LinoxGH) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java:165]:
```suggestion
                if (System.currentTimeMillis() - capturedConf.getLong("captureTime") < MIN_THAW_DELAY) {
```

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java [hunk 8]
```diff
@@ -179,36 +189,48 @@ private YamlConfiguration freezeEntity(Animals target) {
...
-            Horse h = (Horse) target;
-            conf.set("horseStyle", h.getStyle().toString());
-            conf.set("horseVariant", h.getVariant().toString());
-            conf.set("horseColor", h.getColor().toString());
-            conf.set("chest", h.isCarryingChest());
+        case MULE:
+        case DONKEY:
+        case ZOMBIE_HORSE:
+        case SKELETON_HORSE:
+            if(target instanceof Horse){
```
Comment (LinoxGH) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java:224]:
```suggestion
            if (target instanceof Horse) {
```

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java [hunk 9]
```diff
@@ -179,36 +189,48 @@ private YamlConfiguration freezeEntity(Animals target) {
...
+                Horse horse = (Horse) target;
+                conf.set("horseStyle", horse.getStyle().toString());
+                conf.set("horseColor", horse.getColor().toString());
+            }
+            if(target instanceof ChestedHorse) {
```
Comment (LinoxGH) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java:229]:
```suggestion
            else if (target instanceof ChestedHorse) {
```

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java [hunk 10]
```diff
@@ -246,33 +268,36 @@ private void thawEntity(Animals entity, Configuration conf) {
             ((Sheep) entity).setSheared(conf.getBoolean("sheared"));
             ((Sheep) entity).setColor(DyeColor.valueOf(conf.getString("color")));
             break;
-        case OCELOT:
-            ((Ocelot) entity).setCatType(Ocelot.Type.valueOf(conf.getString("catType")));
+        case CAT:
+            ((Cat) entity).setCatType(Type.valueOf(conf.getString("catType")));
+            ((Cat) entity).setCollarColor(DyeColor.valueOf(conf.getString("collarColor")));
```
Comment (LinoxGH) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java:273]: Instead of casting twice assign a variable.

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java [hunk 11]
```diff
@@ -246,33 +268,36 @@ private void thawEntity(Animals entity, Configuration conf) {
...
             break;
         case WOLF:
             ((Wolf) entity).setSitting(conf.getBoolean("sitting"));
-            ((Wolf) entity).setCollarColor(DyeColor.valueOf(conf.getString("collar")));
+            ((Wolf) entity).setCollarColor(DyeColor.valueOf(conf.getString("collarColor")));
```
Comment (LinoxGH) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java:277]: Assign a var here too.

**Review by LinoxGH — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java [hunk 12]
```diff
@@ -247,36 +274,43 @@ private void thawEntity(Animals entity, Configuration conf) {
...
-                h.getInventory().setArmor(new ItemStack(Material.getMaterial(conf.getString("armor"))));
+        case MULE:
+        case DONKEY:
+        case ZOMBIE_HORSE:
+        case SKELETON_HORSE:
+            if (entity instanceof Horse) {
+                Horse h = (Horse) entity;
+                h.setColor(Horse.Color.valueOf(conf.getString("horseColor")));
+                h.setStyle(Horse.Style.valueOf(conf.getString("horseStyle")));
+            } else if (entity instanceof ChestedHorse) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/sensibletoolbox/items/EnderLeash.java:300]: The `else if` should go on the next line after the bracket to be consistent with the rest of the file.

**Review by LinoxGH — APPROVED** [review]
1 last thing is adding `break;` to horse cases.

**Review by TheBusyBiscuit — APPROVED** [review]

**Comment by TheBusyBiscuit** [comment]
@LinoxGH What do you mean? There is a `break;` statement

**Comment by LinoxGH** [comment]
> @LinoxGH What do you mean? There is a `break;` statement

Oops it wasn't shown in the review changes section. If it is then no problems
